export const TOK = {
  bg:        '#0a0a0f',
  surface:   '#111118',
  surface2:  '#16161e',
  surface3:  '#1d1d28',
  surface4:  '#252531',
  border:    '#272735',
  borderHi:  '#3a3a4e',
  text:      '#eef0f6',
  textSec:   '#b3b5c2',
  textDim:   '#7e8090',
  textMute:  '#54566a',
  indigo:    '#6366f1',
  indigoHi:  '#818cf8',
  indigoSoft:'#1e1e3a',
  violet:    '#a78bfa',
  coral:     '#ff6b6b',
  coralHi:   '#ff8585',
  coralSoft: '#3a1c20',
  sky:       '#5fb3ff',
  skyHi:     '#7cc3ff',
  skySoft:   '#1a2738',
  green:     '#4ade80',
  greenSoft: '#0d2118',
  amber:     '#fbbf24',
  amberSoft: '#2a1f0a',
  rose:      '#f87171',
  roseSoft:  '#2a1416',
  serif:     '"Fraunces", "Instrument Serif", Georgia, serif',
  italic:    '"Instrument Serif", Georgia, serif',
  sans:      '"Inter", -apple-system, BlinkMacSystemFont, sans-serif',
  mono:      '"JetBrains Mono", ui-monospace, monospace',
};

export const TR = {
  continue:     'Devam et',
  start:        'Başla',
  back:         'Geri',
  next:         'İleri',
  finish:       'Bitir',
  cancel:       'İptal',
  save:         'Kaydet',
  send:         'Gönder',
  search:       'Ara',
  loading:      'Yükleniyor',
  learn:        'Öğren',
  progress:     'İlerleme',
  library:      'Kitaplık',
  tutor:        'Eğitmen',
  account:      'Hesap',
  level:        'Seviye',
  unit:         'Ünite',
  lesson:       'Ders',
  theory:       'Kuram',
  practice:     'Alıştırma',
  reading:      'Okuma',
  workshop:     'Yazı atölyesi',
  exam:         'Sınav',
  vocabulary:   'Sözcükler',
  streak:       'Seri',
  xp:           'PX',
  hearts:       'Can',
  welcome:      'Tekrar hoş geldin',
  signIn:       'Giriş yap',
  signUp:       'Hesap oluştur',
  email:        'E-posta',
  password:     'Şifre',
  forgot:       'Şifremi unuttum',
  rightAnswer:  'Doğru!',
  wrongAnswer:  'Yanlış',
  tryAgain:     'Tekrar dene',
  goodMorning:  'Günaydın',
  saveWord:     'Sözcüğü kaydet',
};
